// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div hx-ext=\"response-targets\" class=\"flex-1 flex flex-col justify-center items-center\"><h1 class=\"text-5xl font-bold mb-4\">Welcome Back</h1><p class=\"text-lg text-gray-600 mb-6 text-center\">Login to continue your journey</p><form hx-post=\"/login\" hx-trigger=\"submit\" hx-target-401=\"#login-error\" class=\"bg-white p-8 rounded-lg shadow-lg w-96\"><div id=\"login-error\"></div><div class=\"mb-4\"><label class=\"block text-gray-700 font-medium\">Email</label> <input type=\"email\" name=\"email\" required class=\"w-full p-3 mt-1 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500\"></div><div class=\"mb-6\"><label class=\"block text-gray-700 font-medium\">Password</label> <input type=\"password\" name=\"password\" required class=\"w-full p-3 mt-1 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500\"></div><button type=\"submit\" class=\"w-full py-3 bg-green-600 text-white font-semibold rounded-lg hover:bg-green-700 transition\">Sign In</button><div class=\"flex justify-between items-center mt-4 text-sm text-gray-600\"><a href=\"/register\" class=\"text-green-600 font-semibold hover:underline\">Register</a> <a href=\"/forgot-password\" class=\"text-green-600 font-semibold hover:underline\">Forgot Password?</a></div></form><a href=\"/auth/google/login\"><img class=\"h-10\" src=\"https://developers.google.com/identity/images/btn_google_signin_dark_normal_web.png\" alt=\"Sign in with Google\"></a></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func LoginError() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p>Invalid Email or Password</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
